ALTER TABLE "Race" ADD COLUMN "saleStartAt" TIMESTAMP(3);
ALTER TABLE "Race" ADD COLUMN "saleEndAt" TIMESTAMP(3);
ALTER TABLE "Race" ADD COLUMN "videoStartedAt" TIMESTAMP(3);
ALTER TABLE "Race" ADD COLUMN "videoFinishedAt" TIMESTAMP(3);
